version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6
    ports:
      - 6379:6379

  centrifugo:
    image: centrifugo/centrifugo:v3.0.5
    volumes:
      - ./conf/centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8001:8001
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
    command: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "60s", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./.env:/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '9000:9000'
    command: 'bash -c "nginx -g ''daemon off;''"'
    depends_on:
      - centrifugo
      - app
