# Generated by Django 4.1.7 on 2023-05-24 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeradminuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.image', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='registeradminuser',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя'),
        ),
        migrations.AddField(
            model_name='account',
            name='cities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сities_for_account', to='webapp.cities', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='account',
            name='family_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_status_for_account', to='accounts.familystatus', verbose_name='Семейный статус'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_for_account', to='accounts.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_for_account', to='accounts.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
