# Generated by Django 4.2.2 on 2023-07-03 14:45

import accounts.models.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about_me',
            field=models.TextField(max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='account',
            name='achievements',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[accounts.models.validators.validate_age], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='account',
            name='companies',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Компании'),
        ),
        migrations.AlterField(
            model_name='account',
            name='education',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='account',
            name='expertise',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Экспертиза'),
        ),
        migrations.AlterField(
            model_name='account',
            name='facts_about_me',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Факты обо мне'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[accounts.models.validators.validate_full_name], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='account',
            name='goal_for_the_year',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Цель на год'),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='account',
            name='industries',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Отрасли'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[accounts.models.validators.validate_full_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[accounts.models.validators.validate_full_name], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='account',
            name='occupation',
            field=models.TextField(max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Род деятельности'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='account',
            name='request',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='account',
            name='resources_available',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ресурсы имеющиеся'),
        ),
        migrations.AlterField(
            model_name='account',
            name='resources_searching',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ресурсы запрашиваемые'),
        ),
        migrations.AlterField(
            model_name='account',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.URLValidator], verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='account',
            name='social_links',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ссылки на социальные сети'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Текст отзыва'),
        ),
    ]
