# Generated by Django 4.1.7 on 2023-05-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        ('accounts', '0003_remove_registeradminuser_avatar_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='сities_for_account', to='webapp.cities', verbose_name='Город'),
        ),
    ]
