# Generated by Django 4.2.2 on 2023-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_privileges'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='privileges',
            field=models.ManyToManyField(to='accounts.privileges', verbose_name='Привилегии'),
        ),
    ]
