# Generated by Django 4.1.7 on 2023-05-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='family_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_status_for_account', to='accounts.familystatus', verbose_name='Семейный статус'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_for_account', to='accounts.status', verbose_name='Статус'),
        ),
    ]
