# Generated by Django 4.2.2 on 2023-06-30 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_about_me_alter_account_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.URLValidator], verbose_name='Сайт'),
        ),
    ]
