# Generated by Django 4.2.2 on 2023-07-01 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='account',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Текст отзыва'),
        ),
    ]
