# Generated by Django 4.2.2 on 2023-06-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_email_alter_account_phone_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dislikes_qty',
        ),
        migrations.AddField(
            model_name='account',
            name='achievements',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='account',
            name='children',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='account',
            name='companies',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Компании'),
        ),
        migrations.AddField(
            model_name='account',
            name='education',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='account',
            name='expertise',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Экспертиза'),
        ),
        migrations.AddField(
            model_name='account',
            name='facts_about_me',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Факты обо мне'),
        ),
        migrations.AddField(
            model_name='account',
            name='goal_for_the_year',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Цель на год'),
        ),
        migrations.AddField(
            model_name='account',
            name='hobby',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Хобби'),
        ),
        migrations.AddField(
            model_name='account',
            name='industries',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Отрасли'),
        ),
        migrations.AddField(
            model_name='account',
            name='request',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='account',
            name='resources_available',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ресурсы имеющиеся'),
        ),
        migrations.AddField(
            model_name='account',
            name='resources_searching',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ресурсы запрашиваемые'),
        ),
        migrations.AddField(
            model_name='account',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='account',
            name='social_links',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылки на социальные сети'),
        ),
    ]
