# Generated by Django 4.1.7 on 2023-05-16 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citi_name', models.CharField(max_length=30, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_name', models.CharField(max_length=30, verbose_name='Мероприятие')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_at', models.DateTimeField(default=None, verbose_name='Дата мероприятия')),
                ('number_of_seats', models.IntegerField(verbose_name='Количество мест')),
                ('start_register_at', models.DateTimeField(default=None, null=True, verbose_name='дата начала регистрации')),
                ('end_register_at', models.DateTimeField(default=None, null=True, verbose_name='дата конца регистрации')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('place', models.CharField(max_length=200, null=True, verbose_name='Место')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_at', models.DateTimeField(default=None, null=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(blank=True, default='user_pic/default_user_pic.jpeg', null=True, upload_to='user_pic', verbose_name='Фото мероприятия')),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сities', to='webapp.cities', verbose_name='Город')),
                ('type_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_events', to='webapp.typeevents', verbose_name='Тип мероприятия')),
                ('user', models.ManyToManyField(blank=True, related_name='Организатор', to=settings.AUTH_USER_MODEL)),
                ('user_booked', models.ManyToManyField(blank=True, related_name='забронировали_место', to=settings.AUTH_USER_MODEL)),
                ('user_paid', models.ManyToManyField(blank=True, related_name='оплатили', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
