# Generated by Django 4.2.2 on 2023-06-30 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='user_pic', validators=[django.core.validators.validate_image_file_extension], verbose_name='Фото'),
        ),
    ]
