# Generated by Django 4.2.2 on 2023-06-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminrequest',
            old_name='closing_at',
            new_name='closed_at',
        ),
    ]
