# Generated by Django 4.1.7 on 2023-05-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='events',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обнавления'),
        ),
    ]
