# Generated by Django 4.1.7 on 2023-06-06 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_events_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameVotingTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_voting_type', models.CharField(max_length=100, verbose_name='Наименование типа голосования')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_to_vote', models.TextField(max_length=100, verbose_name='Вопрос на голосование')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обнавления голосования')),
            ],
        ),
        migrations.CreateModel(
            name='VotingTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_value', models.BooleanField(default=True, verbose_name='Булева значение')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_type', to='webapp.vote', verbose_name='Голосование типы')),
                ('voting_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_voting_types', to='webapp.namevotingtypes', verbose_name='Тип голосования')),
            ],
        ),
        migrations.CreateModel(
            name='VotingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(max_length=100, verbose_name='Вариант')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления варианта')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаление варианта')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_options', to='webapp.vote', verbose_name='Голосование опции')),
            ],
        ),
        migrations.CreateModel(
            name='UsersWhoVoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_at', models.DateTimeField(auto_now=True, verbose_name='Дата ответа')),
                ('possible_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possible_answer', to='webapp.votingoptions', verbose_name='Вариант ответа')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
        migrations.CreateModel(
            name='ListVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_vote', models.CharField(max_length=200, verbose_name='Наименование голосования')),
                ('date_group_was_added_from_polls', models.DateTimeField(auto_now=True, verbose_name='Дата добавления группу из голосований')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления списка')),
                ('voting_opening_at', models.DateTimeField(auto_now=True, verbose_name='Дата открытия голосования')),
                ('expiration_at', models.DateTimeField(auto_now=True, verbose_name='Дата окончания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено голосования')),
                ('user_who_created_list_votes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший список из голосований')),
                ('vote', models.ManyToManyField(related_name='vote_list', to='webapp.vote', verbose_name='Голосование список')),
            ],
        ),
        migrations.CreateModel(
            name='AttachingToBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата добавления голосования')),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='webapp.events', verbose_name='Мероприятия')),
                ('list_of_votes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_votes', to='webapp.listvotes', verbose_name='Список голосования')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='webapp.news', verbose_name='Новости')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь которому дали список из голосований')),
            ],
        ),
    ]
