# Generated by Django 4.1.7 on 2023-05-16 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_events_price_alter_events_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='events',
            name='user_booked',
            field=models.ManyToManyField(blank=True, related_name='user_booked', to=settings.AUTH_USER_MODEL, verbose_name='забронировали_место'),
        ),
        migrations.AlterField(
            model_name='events',
            name='user_paid',
            field=models.ManyToManyField(blank=True, related_name='user_paid', to=settings.AUTH_USER_MODEL, verbose_name='оплатили'),
        ),
    ]
