# Generated by Django 4.2.2 on 2023-06-29 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_subscriptionlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('closing_at', models.DateTimeField(default=None, null=True, verbose_name='Дата закрытия')),
                ('approved', models.BooleanField(default=True, null=True, verbose_name='Удалено')),
                ('request_text', models.TextField(max_length=3000, null=True, verbose_name='Текст запроса')),
                ('response_text', models.TextField(max_length=3000, null=True, verbose_name='Ответ админа')),
                ('cities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_level', to='webapp.subscriptionlevel', verbose_name='Запрос на подписку')),
                ('user_reviewer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
                ('user_sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
        ),
    ]
