# Generated by Django 4.2.2 on 2023-06-29 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_adminrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminrequest',
            old_name='cities',
            new_name='sub_level',
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('cities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='сities_chat_request', to='webapp.cities', verbose_name='Город')),
                ('second_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_second_user', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='chat_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_admin_request', to='webapp.chatrequest', verbose_name='Запрос на создание чата'),
        ),
    ]
