# Generated by Django 4.1.7 on 2023-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_events_user_alter_events_user_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование'),
        ),
    ]
