# Generated by Django 4.2.2 on 2023-06-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_cities_adminrequest_sub_level_chatrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrequest',
            old_name='name',
            new_name='chat_name',
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='rules',
            field=models.TextField(default=None, max_length=3000, verbose_name='Правила'),
        ),
    ]
