# Generated by Django 4.1.7 on 2023-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_events_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
    ]
