# Generated by Django 4.2.2 on 2023-06-29 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_rename_name_chatrequest_chat_name_chatrequest_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='second_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_second_user', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь'),
        ),
    ]
