# Generated by Django 4.1.7 on 2023-05-22 12:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_image_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
        migrations.RemoveField(
            model_name='events',
            name='user_booked',
        ),
        migrations.RemoveField(
            model_name='events',
            name='user_paid',
        ),
        migrations.AddField(
            model_name='events',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='events',
            name='cities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='сities', to='webapp.cities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_register_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца регистрации'),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_at',
            field=models.DateTimeField(verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='events',
            name='number_of_seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_register_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата начала регистрации'),
        ),
        migrations.CreateModel(
            name='UserBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('date_of_payment', models.DateTimeField(blank=True, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.events', verbose_name='Мероприятие')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Забронировал')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='resident_booked',
            field=models.ManyToManyField(blank=True, related_name='user_booked', through='webapp.UserBooked', to=settings.AUTH_USER_MODEL, verbose_name='Бранированные резиденты'),
        ),
    ]
