# Generated by Django 4.2.2 on 2023-06-29 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_alter_chatrequest_second_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrequest',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Утвержден?'),
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='closing_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='request_text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текст запроса'),
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='response_text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Ответ админа'),
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='user_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий'),
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
