# Generated by Django 4.2.2 on 2023-07-03 14:45

import django.core.validators
from django.db import migrations, models
import webapp.models.events


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_adminrequest_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrequest',
            name='request_text',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Текст запроса'),
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='response_text',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ответ админа'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_register_at',
            field=models.DateTimeField(blank=True, null=True, validators=[webapp.models.events.validate_date_event], verbose_name='Дата конца регистрации'),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_at',
            field=models.DateTimeField(validators=[webapp.models.events.validate_date_event], verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='events',
            name='place',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_register_at',
            field=models.DateTimeField(default=None, null=True, validators=[webapp.models.events.validate_date_event], verbose_name='Дата начала регистрации'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='user_pic', validators=[django.core.validators.validate_image_file_extension], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='listvotes',
            name='name_of_the_vote',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Наименование голосования'),
        ),
        migrations.AlterField(
            model_name='namevotingtypes',
            name='name_of_voting_type',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Наименование типа голосования'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='question_to_vote',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Вопрос на голосование'),
        ),
        migrations.AlterField(
            model_name='votingoptions',
            name='option',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Вариант'),
        ),
    ]
